sudo: required
dist: trusty
git:
  depth: 1
language:
- c
install:
- sudo apt-get install -y install lzop libc6-i386 lib32stdc++6 lib32z1
- wget -c https://releases.linaro.org/14.09/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
- tar xf gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux.tar.xz
- export PATH="${PWD}/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin":"${PATH}"

script:
- which arm-linux-gnueabihf-gcc
